### ISSUE TITLE
Infrastructure Pipeline fails for Codepipeline using Source Action Provider as Github Apps to access the Repositories

### ISSUE THREAD

**Issue by AditModi** [aws-samples/aws-cdk-pipelines-datalake-infrastructure#12]
The Infrastructure Pipeline fails when the source action is changed from using personal access token to github app to access the repositories.
The AWS Codepipeline recommends using github apps to access the repositories.

**Comment by igrant-2ndWatch** [comment]
@AditModi

Can you provide more information on how you are utilizing a Github App and the error which is being produced? You should be able to replace the `GitHubSourceAction` we use in this example with the `CodeStarConnectionsSourceAction`.

This will require an active/available CodeStar connection that was [created via console or CLI](https://docs.aws.amazon.com/codepipeline/latest/userguide/connections-github.html#connections-github-cli).

References:

* [AWS CDK - CodeStarConnectionsSourceAction](https://docs.aws.amazon.com/cdk/api/latest/python/aws_cdk.aws_codepipeline_actions/CodeStarConnectionsSourceAction.html)
* [AWS CDK - Original feature request](https://github.com/aws/aws-cdk/issues/10632)

**Comment by itharavi** [comment]
Closing the issue based on response from @igrant-2ndWatch to the original question. @AditModi - if you still have issues, please re-create a new issue with more details on the errors per @igrant-2ndWatch
